FROM registry.fedoraproject.org/fedora-minimal

RUN microdnf install python3 python3-qpid-proton python3-flask && microdnf clean all

ADD connect.json /etc/messaging/connect.json
ADD main.py /app/main.py
ADD moonisland.py /app/moonisland.py

ENTRYPOINT ["python3", "/app/main.py"]
