apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
  labels:
    app: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
        - name: message-broker
          image: quay.io/artemiscloud/activemq-artemis-broker
          env:
            - name: AMQ_USER
              value: admin
            - name: AMQ_PASSWORD
              value: peripatetic-possum
          ports:
            - containerPort: 5672
